---
- name: Verificando
  hosts: all
  gather_facts: yes
  become: yes


  vars_prompt:
    - name: "interface_name"
      prompt: "Informe o nome da Interface"
    - name: "ip"
      prompt: "Informe o IP"
    - name: "mascara"
      prompt: "Informe a mascara"
    - name: "x"
      prompt: "Adição de Rota para Backup Escolha 0(zero) para x e 1(um) para y"
    - name: "gw"
      prompt: "Informe qual o GW da rede de Backup"


  vars:
    interface_name:  "{{interface_name}}"
    ip: "{{ip}}"
    mascara: "{{mascara}}"
    x: "{{x}}"

  tasks:


  - name: Criar arquivos
    file:
      path: '{{item.arquivo}}'
      state: touch
    with_items:
          - { arquivo: '/etc/sysconfig/network-scripts/ifcfg-{{interface_name}}' }
          - { arquivo: '/etc/sysconfig/network-scripts/route-{{interface_name}}' }


  - name: Configurando IP 
    blockinfile:
     path: "/etc/sysconfig/network-scripts/ifcfg-{{interface_name}}"
     block: |
       TYPE=Ethernet
       BOOTPROTO=static
       NAME=enp0s8
       DEVICE=enp0s8
       ONBOOT=yes
       IPADDR={{ip}}
       NETMASK={{mascara}} 

  - name: "Inserindo Rotas da x"
    blockinfile:
     path: "/etc/sysconfig/network-scripts/route-{{interface_name}}"
     block: |
       #ROTAS PARA O X
        200.98.32.208/28 via {{gw}}
        200.98.43.0/24 via {{gw}}   
    when: x == '0' 



  - name: "Inserindo Rotas da Y"
    blockinfile:
     path: "/etc/sysconfig/network-scripts/route-{{interface_name}}"
     block: |
      #ROTAS PARA O AVAMAR Y
      200.221.192.208/28 via {{gw}}
      200.221.203.0/24 via {{gw}}
    when: x == '1'

  - name: Habilitando Interface de rede
    shell: "ifdown {{interface_name}} && ifup {{interface_name}}"
